### ISSUE TITLE
xcode 图片不能旋转

### ISSUE THREAD

**Issue by godfery** [johnhany/textRotCorrect#1]
图片用你共享出来的http://pan.baidu.com/s/1bnaNmmb

程序也一点没有改变。

运行不能旋转，

输出
the rotation angel to be applied:
0

这是为什么呢？

**Comment by johnhany** [comment]
频谱图像是什么样子 能看出一条明显的直线吗？
不同的图片可能需要调整GRAY_THRESH和HOUGH_VOTE两个参数才能达到最好的效果 以直线检测结果中只有一条倾斜直线为准
